# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:16.0.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-v1-{{ .Branch }}-{{ .Revision }}
            - dependencies-v1-{{ .Branch }}-
            - dependencies-v1-master-
            - dependencies-v1-

      # run build
      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
            - .gradle/loom-cache
          key: dependencies-v1-{{ .Branch }}-{{ .Revision }}

      - store_artifacts:
          path: build/libs
          destination: .
